services:
  - type: web
    name: linebook-api
    env: python
    region: singapore
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      pip install eval_type_backport "bcrypt==4.0.1"
      alembic upgrade head
      python seed.py
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: linebook-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: 31caaddd4fbd8c26373b7cc721a867757f6233414732776e164da238edb8fc8b
      - key: APP_SECRET_KEY
        value: 32af8fe66ca37b44dd49496544ee26a20115ea5e54d62c9f82f47366db15388f
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        value: ab23ccddbcfc223799e93dc1d3a9c805
      - key: LINE_LIFF_ID
        value: 2009586205-CyS3JZM7
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: CORS_ORIGINS
        sync: false

databases:
  - name: linebook-db
    databaseName: linebook
    plan: free
    region: singapore
